// Sample theme to demonstrate the gallery + demand page layout.
// Delete this folder once your first real theme ships.

import Link from "next/link";

export const metadata = {
  title: "Sample Demo — AI Automation Factory",
  description: "This is a sample demand page showing the layout.",
};

export default function SampleDemoPage() {
  return (
    <article>
      <div className="border-b border-border bg-accent-soft">
        <div className="max-w-5xl mx-auto px-6 py-3 text-sm">
          <Link href="/" className="text-muted hover:text-foreground transition">
            ← All demos
          </Link>
          <span className="text-border mx-3">/</span>
          <span className="text-muted">Sample category</span>
        </div>
      </div>

      <section className="px-6 py-20 md:py-28 max-w-5xl mx-auto">
        <p className="text-xs font-medium uppercase tracking-widest text-muted mb-4">
          Sample category
        </p>
        <h1 className="text-4xl md:text-6xl font-semibold tracking-tight leading-tight mb-6">
          Sample Demo Theme
        </h1>
        <p className="text-lg md:text-xl text-muted max-w-2xl mb-10 leading-relaxed">
          This is what every demand page looks like — a real demo with real copy
          generated by the factory pipeline. The card on the homepage links here.
        </p>
        <a
          href="#cta"
          className="inline-flex items-center justify-center rounded-md bg-foreground text-background px-6 py-3 text-base font-medium hover:opacity-90 transition"
        >
          Get in touch
        </a>
      </section>

      <section className="px-6 py-20 border-t border-border">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl font-semibold tracking-tight mb-10">
            What&apos;s included
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            <Feature
              title="Approved demand"
              body="Every theme starts from a real signal the factory surfaced and you approved in Telegram."
            />
            <Feature
              title="AI-generated copy"
              body="Hero, features, and CTA copy written by Claude based on the demand pattern."
            />
            <Feature
              title="Auto-deployed"
              body="From approval to live URL in under 3 minutes via GitHub Actions + Vercel."
            />
          </div>
        </div>
      </section>

      <section id="cta" className="px-6 py-20 border-t border-border bg-accent-soft">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl font-semibold tracking-tight mb-4">
            Want one of these for your business?
          </h2>
          <p className="text-muted mb-8">
            Reach out and we&apos;ll build it.
          </p>
          <a
            href="mailto:hello@alexisruiz1040.com"
            className="inline-flex items-center justify-center rounded-md bg-foreground text-background px-6 py-3 text-base font-medium hover:opacity-90 transition"
          >
            Get in touch
          </a>
        </div>
      </section>

      <div className="px-6 py-8 border-t border-border">
        <div className="max-w-5xl mx-auto text-xs text-muted font-mono">
          Theme slug: sample-demo · Built 2026-05-26
        </div>
      </div>
    </article>
  );
}

function Feature({ title, body }: { title: string; body: string }) {
  return (
    <div>
      <h3 className="text-lg font-semibold mb-2">{title}</h3>
      <p className="text-muted leading-relaxed">{body}</p>
    </div>
  );
}
